# Configuração da Porta para o Deploy (Railway/AWS)
server.port=${PORT:8080}

# Conexão com o Banco de Dados (PostgreSQL no Railway)
spring.datasource.url=jdbc:postgresql://crossover.proxy.rlwy.net:57149/railway
spring.datasource.username=postgres
spring.datasource.password=BzSVNWtfesRfbhSebuHfnjKEbGRylpUX
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Hibernate não tente validar a conexão antes dela existir
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true